# Generated by Django 4.0.6 on 2022-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('millage', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
