# Generated by Django 4.0.6 on 2022-08-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
    ]
